name: Check and SOPS

on:
  push:
    branches:
      - "action/test"
jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          java-version: [ 17 ]
      steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: Sops Binary Installer
          uses: mdgreenwald/mozilla-sops-action@v1.4.1
          with:
            version: '<version>' # default is latest stable
          id: install